version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["npm", "start"]
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/usr/src/backend
    environment:
      - NODE_ENV=production
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - frontend_data:/usr/src/frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on: 
      - backend
    image: eruobodo/myname:latest
volumes:
  backend_data:
    driver: local
  frontend_data:
    driver: local
